Tested Version
Had to fix all the functions since it was being called without loop in the parameters.

Error given when testing:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/juansanchez/Documents/GitHub/BUS_392_Project/Lanzix2.py", line 1218, in <module>
    main()
  File "/Users/juansanchez/Documents/GitHub/BUS_392_Project/Lanzix2.py", line 875, in main
    health = wait_sequence(health, inventory, active_effects, achievements, loop)
  File "/Users/juansanchez/Documents/GitHub/BUS_392_Project/Lanzix2.py", line 456, in wait_sequence
    health = battle_code_killer_2(aaron, health, inventory, active_effects, achievements, loop)
  File "/Users/juansanchez/Documents/GitHub/BUS_392_Project/Lanzix2.py", line 397, in battle_code_killer_2
    loop[0] = 1  # Respawn at the first loop
TypeError: 'int' object does not support item assignment